lib/ex_money_web/router.ex
defmodule ExMoney.Web.Router do
  use ExMoney.Web, :router

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :saltedge_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  pipeline :api_auth do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader, realm: "Token"
    plug Guardian.Plug.LoadResource
  end

  scope "/", ExMoney.Web do
    pipe_through [:browser, :browser_session]

    get "/", DashboardController, :overview

    get "/login", SessionController, :new, as: :login
    get "/setup/new", SetupController, :new
    post "/setup/complete", SetupController, :complete
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :delete, as: :logout
    get "/logout", SessionController, :delete, as: :logout

    scope "/dashboard" do
      get "/", DashboardController, :overview
      get "/overview", DashboardController, :overview
    end

    scope "/settings", Settings, as: :settings do
      get "/user", UserController, :edit
      put "/user", UserController, :update
      resources "/accounts", AccountController
      get "/categories/sync", CategoryController, :sync
      resources "/categories", CategoryController
      resources "/rules", RuleController
      resources "/logins", LoginController, only: [:index, :delete, :show]
    end

    resources "/transactions", TransactionController
  end

  scope "/m", ExMoney.Web.Mobile, as: :mobile do
    pipe_through [:browser, :browser_session]

    get "/", StartController, :index
    get "/dashboard", DashboardController, :overview
    get "/overview", DashboardController, :overview
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    get "/accounts/:id/refresh", AccountController, :refresh
    get "/accounts/:id/expenses", AccountController, :expenses
    get "/accounts/:id/income", AccountController, :income
    resources "/accounts", AccountController, only: [:show]
    resources "/transactions", TransactionController
    post "/transactions/create_from_fav", TransactionController, :create_from_fav

    resources "/favourite_transactions", FavouriteTransactionController do
      put "/fav", FavouriteTransactionController, :fav, as: :fav, param: "id"
    end

    get "/budget", BudgetController, :index
    get "/budget/expenses", BudgetController, :expenses
    get "/budget/income", BudgetController, :income
    resources "/budget_history", BudgetHistoryController, only: [:index, :show]

    scope "/settings", as: :setting do
      get "/", SettingController, :index
      resources "/budget", Setting.BudgetController, only: [:new, :show, :edit, :update, :create], singleton: true do
        post "/apply", Setting.BudgetController, :apply
      end
      resources "/budget_items", Setting.BudgetItemController, only: [:delete]

      resources "/categories", Setting.CategoryController, only: [:index, :edit, :update]
    end
  end

  scope "/saltedge", ExMoney.Web.Saltedge, as: :saltedge do
    pipe_through [:browser, :browser_session]

    scope "/logins" do
      get "/new", LoginController, :new
      get "/:id/sync", LoginController, :sync
    end

    scope "/accounts" do
      get "/sync", AccountController, :sync
    end
  end

  scope "/callbacks", ExMoney.Web.Callbacks, as: :callbacks do
    pipe_through [:saltedge_api, :browser_session]

    post "/success", SuccessCallbackController, :success, as: :success
    post "/failure", FailureCallbackController, :failure, as: :failure
    post "/notify", NotifyCallbackController, :notify, as: :notify
    post "/interactive", InteractiveCallbackController, :interactive, as: :interactive
    post "/destroy", DestroyCallbackController, :destroy, as: :destroy
  end

  scope "/api/v2", ExMoney.Web.Api.V2, as: :api do
    pipe_through [:api_auth]

    post "/login", SessionController, :login
    resources "/accounts", AccountController, only: [:index]
    resources "/categories", CategoryController, only: [:index]
    get "/transactions/recent", TransactionController, :recent, as: :recent
  end

  scope "/api/v1", ExMoney.Web.Api.V1, as: :api do
    pipe_through [:api]
    get "/session/relogin", SessionController, :relogin
  end
end

lib/ex_money_web/controllers/api/v2/account_controller.ex
defmodule ExMoney.Web.Api.V2.AccountController do
  use ExMoney.Web, :controller

  alias ExMoney.Account

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.ApiUnauthenticated

  def index(conn, _params) do
    user = Guardian.Plug.current_resource(conn)

    accounts = Account.by_user_id(user.id) |> Repo.all

    render conn, :index, accounts: accounts
  end
end

lib/ex_money_web/controllers/mobile/account_controller.ex
defmodule ExMoney.Web.Mobile.AccountController do
  use ExMoney.Web, :controller

  alias ExMoney.DateHelper
  alias ExMoney.{Repo, Transaction, Account}

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def show(conn, %{"id" => account_id} = params) do
    parsed_date = DateHelper.parse_date(params["date"])
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    account = Account.by_id_with_login(account_id) |> Repo.one

    month_transactions = Transaction.by_month(account_id, from, to)
    |> Repo.all

    categories = Transaction.group_by_month_by_category(account_id, from, to)
    |> Repo.all
    |> Enum.reduce(%{}, fn({category, amount}, acc) ->
      {float_amount, _} = Decimal.to_string(amount, :normal)
      |> Float.parse

      positive_float = float_amount * -1

      Map.put(acc, category.id,
        %{
          id: category.id,
          humanized_name: category.humanized_name,
          css_color: category.css_color,
          amount: positive_float,
          parent_id: category.parent_id
        })
    end)

    current_month = DateHelper.current_month(parsed_date)
    previous_month = DateHelper.previous_month(parsed_date)
    next_month = DateHelper.next_month(parsed_date)

    render conn, :show,
      account: account,
      month_transactions: month_transactions,
      categories: categories,
      current_month: current_month,
      previous_month: previous_month,
      next_month: next_month
  end

  def refresh(conn, %{"id" => account_id}) do
    account = Repo.get(Account, account_id)

    render conn, :refresh, account: account
  end

  def expenses(conn, %{"date" => date, "id" => account_id}) do
    account = Repo.get!(Account, account_id)
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)
    account_balance = account_balance(from, to, account.id)

    scope = Transaction.expenses_by_month(account_id, from, to)
    expenses = fetch_and_process_transactions(scope)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/accounts/#{account_id}/expenses?date=#{date}")

    render conn, :expenses,
      expenses: expenses,
      date: %{label: formatted_date, value: date},
      from: from,
      account: account,
      account_balance: account_balance
  end

  def income(conn, %{"date" => date, "id" => account_id}) do
    account = Repo.get!(Account, account_id)
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)
    account_balance = account_balance(from, to, account.id)

    scope = Transaction.income_by_month(account_id, from, to)
    income = fetch_and_process_transactions(scope)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/accounts/#{account_id}/income?date=#{date}")

    render conn, :income,
      income: income,
      date: %{label: formatted_date, value: date},
      from: from,
      account: account,
      account_balance: account_balance
  end

  defp account_balance(from, to, account_id) do
    ExMoney.Accounts.get_account_history_balance(from, to)
    |> Enum.reduce(%{}, fn(history, acc) ->
      inserted_at =
        history.inserted_at
        |> NaiveDateTime.to_date()
        |> Date.to_string()

      Map.put(acc, inserted_at, history.state[to_string(account_id)])
    end)
  end

  defp fetch_and_process_transactions(scope) do
    scope
    |> Repo.all
    |> Enum.group_by(fn(transaction) -> transaction.made_on end)
    |> Enum.sort(fn({date_1, _transactions}, {date_2, _transaction}) ->
      Date.compare(date_1, date_2) != :lt
    end)
  end
end

lib/ex_money_web/controllers/mobile/budget_controller.ex
defmodule ExMoney.Web.Mobile.BudgetController do
  use ExMoney.Web, :controller

  alias ExMoney.DateHelper
  alias ExMoney.{Repo, Transaction, Budget}

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def index(conn, params) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one

    if current_budget do
      _index(conn, params, current_budget)
    else
      render conn, :setup
    end
  end

  defp _index(conn, params, current_budget) do
    parsed_date = DateHelper.parse_date(params["date"])
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    account_ids = current_budget.accounts
    month_transactions = Transaction.by_month(account_ids, from, to)
    |> Repo.all

    categories = Transaction.group_by_month_by_category_without_withdraw(account_ids, from, to)
    |> Repo.all

    current_month = DateHelper.current_month(parsed_date)
    previous_month = DateHelper.previous_month(parsed_date)
    next_month = DateHelper.next_month(parsed_date)

    currency_label = if month_transactions != [] do
      List.first(month_transactions).account.currency_label
    else
      ""
    end

    categories_limits = Enum.reduce current_budget.items, %{}, fn({item_id, limit}, acc) ->
      {item_id, _} = Integer.parse(item_id)
      {limit, _} = Integer.parse(limit)
      Map.put(acc, item_id, limit)
    end

    render conn, :index,
      month_transactions: month_transactions,
      categories_limits: categories_limits,
      currency_label: currency_label,
      categories: categories,
      current_month: current_month,
      previous_month: previous_month,
      next_month: next_month
  end

  def expenses(conn, %{"date" => date}) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    scope = Transaction.expenses_by_month(current_budget.accounts, from, to)
    expenses = fetch_and_process_transactions(scope)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/budget/expenses?date=#{date}")

    render conn, :expenses,
      expenses: expenses,
      date: %{label: formatted_date, value: date},
      from: from
  end

  def income(conn, %{"date" => date}) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    scope = Transaction.income_by_month(current_budget.accounts, from, to)
    income = fetch_and_process_transactions(scope)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/budget/income?date=#{date}")

    render conn, :income,
      income: income,
      date: %{label: formatted_date, value: date},
      from: from
  end

  defp fetch_and_process_transactions(scope) do
    scope
    |> Repo.all
    |> Enum.group_by(fn(transaction) -> transaction.made_on end)
    |> Enum.sort(fn({date_1, _transactions}, {date_2, _transaction}) ->
      Date.compare(date_1, date_2) != :lt
    end)
  end
end

lib/ex_money_web/controllers/mobile/budget_history_controller.ex
defmodule ExMoney.Web.Mobile.BudgetHistoryController do
  use ExMoney.Web, :controller

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  alias ExMoney.{Repo, Budget, Account, Category}

  def index(conn, _params) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one
    budgets = Budget.by_user_id(user.id) |> Repo.all()

    budgets = if current_budget do
      Enum.reject(budgets, fn(budget) -> budget.id == current_budget.id end)
    else
      budgets
    end

    render conn, :index,
      current_budget: current_budget,
      budgets: budgets
  end

  def show(conn, %{"id" => id}) do
    budget = Repo.get!(Budget, id)
    accounts =
      Enum.map(budget.accounts, fn(account_id) ->
        Repo.get(Account, account_id).name
      end) |> Enum.join(",")

    items =
      budget.items
      |> Enum.map(fn({id, v}) ->
        name = Repo.get(Category, id).humanized_name
        {amount, _} = Integer.parse(v)
        {name, amount}
      end)
      |> Enum.sort(fn({_name_1, amount_1}, {_name_2, amount_2}) -> amount_1 > amount_2 end)

    budget_expenses =
      items
      |> Enum.map(fn({_, amount}) -> amount end)
      |> Enum.sum

    render conn, :show,
      budget_expenses: budget_expenses,
      budget: budget,
      items: items,
      accounts: accounts
  end
end

lib/ex_money_web/controllers/mobile/dashboard_controller.ex
defmodule ExMoney.Web.Mobile.DashboardController do
  use ExMoney.Web, :controller

  alias ExMoney.{Repo, Transaction, Account, FavouriteTransaction}

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def overview(conn, _params) do
    user = Guardian.Plug.current_resource(conn)
    last_login_at = fetch_last_login_at()
    transactions = Transaction.recent(user.id) |> Repo.all

    new_recent_transactions = Enum.filter(transactions, fn(tr) ->
      NaiveDateTime.compare(tr.inserted_at, last_login_at) != :lt
    end)

    new_transaction_ids = Enum.map(new_recent_transactions, fn(tr) -> tr.id end)

    recent_transactions = Enum.group_by(transactions, fn(transaction) ->
      transaction.made_on
    end)
    |> Enum.sort(fn({date_1, _transactions_1}, {date_2, _transactions_2}) ->
      Date.compare(date_1, date_2) != :lt
    end)

    accounts = Account.show_on_dashboard
    |> Repo.all
    |> Enum.reduce([], fn(account, acc) ->
      new_transactions = Transaction.new_since(last_login_at, account.id) |> Repo.all

      recent_diff = Enum.reduce(new_transactions, Decimal.new(0), fn(transaction, acc) ->
        Decimal.add(acc, transaction.amount)
      end)

      [Map.put(account, :recent_diff, recent_diff) | acc]
    end)

    render conn, :overview,
      recent_transactions: recent_transactions,
      accounts: accounts,
      new_transaction_ids: new_transaction_ids,
      fav_transaction: fav_transaction(user.id),
      changeset: Transaction.changeset_custom(%Transaction{})
  end

  defp fav_transaction(user_id) do
    FavouriteTransaction.fav_by_user_id(user_id)
    |> Repo.one
  end

  defp fetch_last_login_at do
    case :ets.lookup(:ex_money_cache, "last_login_at") do
      [] ->
        NaiveDateTime.from_erl!(:calendar.universal_time)
      [{_key, nil}] ->
        NaiveDateTime.from_erl!(:calendar.universal_time)
      [{_key, value}] ->
        value
    end
  end
end

lib/ex_money_web/controllers/mobile/session_controller.ex
defmodule ExMoney.Web.Mobile.SessionController do
  use ExMoney.Web, :controller

  alias ExMoney.{Repo, User}

  plug :put_layout, "mobile.html"

  def new(conn, _params) do
    user = Guardian.Plug.current_resource(conn)

    if user do
      redirect(conn, to: "/m")
    else
      changeset = User.login_changeset(%User{})
      render(conn, ExMoney.Web.Mobile.SessionView, :new, changeset: changeset)
    end
  end

  def create(conn, params = %{}) do
    user = Repo.one(User.by_email(params["user"]["email"] || ""))
    if user do
      changeset = User.login_changeset(user, params["user"])
      if changeset.valid? do
        store_last_login_at(user.last_login_at)
        update_last_login_at(user)

        conn = Guardian.Plug.sign_in(conn, user)
        send_resp(conn, 200, Guardian.Plug.current_token(conn))
      else
        send_resp(conn, 401, "Unauthenticated")
      end
    else
      send_resp(conn, 401, "Unauthenticated")
    end
  end

  defp update_last_login_at(user) do
    User.update_changeset(user, %{last_login_at: NaiveDateTime.utc_now()})
    |> Repo.update
  end

  defp store_last_login_at(timestamp) do
    case :ets.lookup(:ex_money_cache, "last_login_at") do
      [] -> :ets.insert(:ex_money_cache, {"last_login_at", timestamp})
      _value -> :ets.update_element(:ex_money_cache, "last_login_at", {2, timestamp})
    end
  end
end

lib/ex_money_web/controllers/mobile/start_controller.ex
defmodule ExMoney.Web.Mobile.StartController do
  use ExMoney.Web, :controller

  plug :put_layout, "mobile.html"

  def index(conn, _params) do
    render conn, :index
  end
end

lib/ex_money_web/templates/mobile/account/expenses.html.eex
<div class="pages">
  <div class="page navbar-fixed" data-page="account-expenses-screen">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="left">
          <a href="/m/accounts/<%= @account.id %>?date=<%= @date.value %>" class="link back" data-force="true" data-ignore-cache="true">
            <i class="icon icon-back"></i>&nbsp; Back
          </a>
        </div>
        <div class="center">Expenses for <%= @date.label %></div>
      </div>
    </div>
    <div class="page-content hide-navbar-on-scroll">
      <div class="list-block reduced-margin media-list">
        <%= render ExMoney.Web.SharedView, "transactions_list.html",
          transactions: @expenses,
          new_transaction_ids: [],
          account: @account,
          account_balance: @account_balance,
          from: @from %>
      </div>
    </div>
  </div>
</div>

lib/ex_money_web/templates/mobile/account/income.html.eex
<div class="pages">
  <div class="page navbar-fixed" data-page="account-income-screen">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="left">
          <a href="/m/accounts/<%= @account.id %>?date=<%= @date.value %>" class="link back" data-force="true" data-ignore-cache="true">
            <i class="icon icon-back"></i>&nbsp; Back
          </a>
        </div>
        <div class="center">Income for <%= @date.label %></div>
      </div>
    </div>
    <div class="page-content hide-navbar-on-scroll">
      <div class="list-block reduced-margin media-list">
        <%= render ExMoney.Web.SharedView, "transactions_list.html",
          transactions: @income,
          new_transaction_ids: [],
          account: @account,
          account_balance: @account_balance,
          from: @from %>
      </div>
    </div>
  </div>
</div>

lib/ex_money_web/templates/mobile/account/refresh.html.eex
<div class="views">
  <div class="view view-main">
    <div class="pages">
      <div class="page navbar-fixed" data-page="account-refresh-screen">
        <div class="navbar">
          <div class="navbar-inner">
            <div class="left">
              <a href="/m/accounts/<%= @account.id %>" class="link back" data-force="true">
                <i class="icon icon-back"></i>&nbsp; Home
              </a>
            </div>
            <div class="center"><%= @account.name %></div>
          </div>
        </div>
        <div class="page-content" id="account-refresh-content" data-login-id="<%= @account.saltedge_login_id %>" data-account-id="<%= @account.id %>">
        </div>
      </div>
    </div>
  </div>
</div>

lib/ex_money_web/templates/mobile/account/show.html.eex
<div class="views">
  <div class="view view-main">
    <div class="pages">
      <div class="page navbar-fixed" data-page="account-screen">
        <div class="navbar">
          <div class="navbar-inner">
            <div class="left">
              <a href="/m/overview" class="link back" data-force="true">
                <i class="icon icon-back"></i>&nbsp; Home
              </a>
            </div>
            <div class="center" id="account_id" data-account-id="<%= @account.id %>"><%= @account.name %></div>
            <%= if @account.login && @account.login.interactive == true do %>
              <div class="right">
                <%= link "Sync", to: mobile_account_path(@conn, :refresh, @account), data: [force: true, "ignore-cache": true] %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="page-content hide-navbar-on-scroll">
          <div class="content-block-title" align="center">
            <div class="row">
              <div class="col-33" align="left">
                <a href="/m/accounts/<%= @account.id %>?date=<%= @previous_month.date %>" class="link back" data-force="true">
                  &#8592; <%= @previous_month.label %>
                </a>
              </div>
              <div class="col-33" id="current_date" data-current-date="<%= @current_month.date %>">
                <%= @current_month.label %>
              </div>
              <div class="col-33" align="right">
                <a href="/m/accounts/<%= @account.id %>?date=<%= @next_month.date %>" class="link" data-ignore-cache="true">
                  <%= @next_month.label %> &#8594;
                </a>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="list-block">
              <ul>
                <li class="item-content">
                  <div class="item-inner">
                    <div class="item-title">Expenses</div>
                    <div class="item-after" style="color: black">
                      <a href='/m/accounts/<%= @account.id %>/expenses?date=<%= @current_month.date %>' data-ignore-cache="true">
                        <%= expenses(@month_transactions) %> <%= @account.currency_label %>
                      </a>
                    </div>
                  </div>
                </li>
                <li class="item-content">
                  <div class="item-inner">
                    <div class="item-title">Income</div>
                    <div class="item-after" style="color: black">
                      <a href='/m/accounts/<%= @account.id %>/income?date=<%= @current_month.date %>' data-force="true" data-ignore-cache="true">
                        <%= income(@month_transactions) %> <%= @account.currency_label %>
                      </a>
                    </div>
                  </div>
                </li>

                <li class="item-content">
                  <div class="item-inner">
                    <div class="item-title">Balance</div>
                    <div class="item-after" style="color: black">
                      <%= balance(@month_transactions) %> <%= @account.currency_label %>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
            <div class="row">
              <div class="container horizontal flat">
                <h3>Top Expenses</h3>
                <%= for {{id, category, color, width, amount}, sub_categories} <- categories_chart_data(@categories) do %>
                  <div class="progress-bar horizontal accordion-item">
                    <a href="#" class="category-bar item-content item-link" style="color: black" data-category-id="<%= id %>">
                      <div class="progress-track">
                        <div class="progress-fill" style="width:<%= width %>; background: <%= color %>">
                          <span><%= :erlang.float_to_binary(amount, decimals: 1) %>&nbsp;<%= raw category %></span>
                        </div>
                      </div>
                    </a>
                    <div class="accordion-item-content" style="margin-left: 20px">
                      <%= if Enum.count(sub_categories) > 0 do %>
                        <div class="progress-bar horizontal">
                          <%= for {id, category, _color, width, amount} <- sub_categories do %>
                            <a href="#" class="category-bar" style="color: black" data-category-id="<%= id %>">
                              <div class="progress-track" style="margin-top: 10px">
                                <div class="progress-fill" style="width:<%= width %>; background: #b3b3b3">
                                  <span><%= :erlang.float_to_binary(amount, decimals: 1) %>&nbsp;<%= raw category %></span>
                                </div>
                              </div>
                            </a>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>